### ISSUE TITLE
logging/error handling

### ISSUE THREAD

**Issue by armandopmj** [projectLiftOff/surpriseHer.server#2]
log comprehensive data on errors and events

**Comment by mLuby** [comment]
decided we'd create a service to aggregate logging behavior

**Comment by mLuby** [comment]
log = debug
log.info
log.error

want stack trace on log.error

**Comment by mLuby** [comment]
create logs/ dir if DNE

**Comment by mLuby** [comment]
capture request params, query string, body that might have caused an error
