### ISSUE TITLE
Send 'duplicate user' error to front-end on POST to /users

### ISSUE THREAD

**Issue by armandopmj** [projectLiftOff/surpriseHer.server#20]
@mLuby we should agree on a error message format to handle all other types of error that we are going to want to send to the front

**Comment by mLuby** [comment]
How about this? Do you need anything other than something to display to the user?
```js
response.data = {
  message: "You can display this to the user"
  error: { blah blah shouldnt display, or maybe even respond with this }
}
```

So far the errors I've been creating have messages like `"user.create failed"` which is not very helpful to the user. But it's hard to tell what actually went wrong—it's usually SQL errors like `'duplicate entry'` or `'missing required field'`. The former means one of the unique fields has the same values (determining which is not super easy), and the later probably one of the required fields is undefined (also not necessarily easy, but could be checked for client-side).

**Comment by mLuby** [comment]
Closing as old.
