### ISSUE TITLE
test browsers signup

### ISSUE THREAD

**Issue by mLuby** [projectLiftOff/surpriseHer.server#43]
users/incomplete
- [x] desktop/IE
- [x] desktop/Chrome
- [x] desktop/Firefox
- [x] desktop/Safari
- [x] iOS/Chrome
- [x] iOS/Safari
- [x] Android/Chrome

users/complete
- [x] desktop/IE
- [x] desktop/Chrome
- [x] desktop/Firefox
- [x] desktop/Safari
- [x] iOS/Chrome
- [x] iOS/Safari
- [x] Android/Chrome

https://dev.windows.com/en-us/microsoft-edge/tools/screenshots/#http://surpriseher.co

**Comment by mLuby** [comment]
desktop safari complete: missing address code submitted highlighted address as well, and was tricky to get it to resubmit.

**Comment by mLuby** [comment]
@armandopmj can you check android's browser?

**Comment by mLuby** [comment]
Also it's worth noting from these MSIE screenshots that internet explorer may be very broken: https://dev.windows.com/en-us/microsoft-edge/tools/screenshots/#http://surpriseher.co

**Comment by armandopmj** [comment]
@mLuby good finds ill test android.  Going to get groceries and eat first!

**Comment by mLuby** [comment]
Closing as this project is deprecated.
